# version: '3'
services:

  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"
      
  server-dev:
    container_name: exam-project-server-dev-1
    build:
      context: ./server

    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules


  mongo-dev:
    image: mongo:6.0.11
    ports:
      - "12345:27017"



  db-dev:
    image: postgres:15.5-bullseye
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "12346:5432"

  admin-dev: 
    container_name: exam-freshcode-admin-dev
    build: 
      context: ./admin
    
    environment:
      NODE_ENV: development
    ports: 
      - "2030:2030"
    depends_on:
      - db-dev
    volumes: 
      - ./admin:/admin
      - /admin/node_modules

volumes:
  server-dev:
